AllCops:
  TargetRubyVersion: 2.3
  TargetRailsVersion: 5.1

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Metrics/LineLength:
  Max: 180

Naming/MethodName:
  Exclude:
    - 'app/models/concerns/foreman_bootdisk/orchestration/**/*'

Rails/SkipsModelValidations:
  Exclude:
    - 'db/migrate/**/*'

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Rails/Date:
  Exclude:
    - 'lib/tasks/**/*'

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/functional/**/*'

Naming/FileName:
  Exclude:
    - 'db/seeds.d/**/*'
