require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.3
  TargetRailsVersion: 5.2
  Exclude:
    - 'release-gem'
    - 'test/**/*'

Rails:
  Enabled: true

Style:
  Enabled: false

Metrics:
  Enabled: false

Naming/MethodName:
  Exclude:
    - 'app/models/concerns/foreman_bootdisk/orchestration/**/*'

Rails/SkipsModelValidations:
  Exclude:
    - 'db/migrate/**/*'

Rails/Date:
  Exclude:
    - 'lib/tasks/**/*'

Naming/FileName:
  Exclude:
    - 'db/seeds.d/**/*'
