AllCops:
  TargetRubyVersion: 2.3
  TargetRailsVersion: 5.1

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Metrics:
  Enabled: false

Naming/MethodName:
  Exclude:
    - 'app/models/concerns/foreman_bootdisk/orchestration/**/*'

Rails/SkipsModelValidations:
  Exclude:
    - 'db/migrate/**/*'

Rails/Date:
  Exclude:
    - 'lib/tasks/**/*'

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/functional/**/*'

Naming/FileName:
  Exclude:
    - 'db/seeds.d/**/*'

# Support both ruby19 and hash_rockets
Style/HashSyntax:
  EnforcedStyle: no_mixed_keys
  Enabled: true

# Both double and single quotes are OK
Style/StringLiterals:
  Enabled: false
